CREATE DATABASE UNIT_4;

USE UNIT_4;

CREATE TABLE HOCSINH(
    MAHS VARCHAR(20) PRIMARY KEY,
    TENHS VARCHAR(50),
    NGAYSINH DATETIME,
    LOP VARCHAR(20),
    GT VARCHAR(20)
);

CREATE TABLE MONHOC(
    MAMH VARCHAR(20) PRIMARY KEY,
    TENMH VARCHAR(50)
);

CREATE TABLE BANGDIEM(
    MAHS VARCHAR(20),
    MAMH VARCHAR(20),
    DIEMTHI INT,
    NGAYKT DATETIME,
    PRIMARY KEY (MAHS, MAMH),
    FOREIGN KEY (MAHS) REFERENCES HOCSINH(MAHS),
    FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
);

CREATE TABLE GIAOVIEN(
    MAGV VARCHAR(20) PRIMARY KEY,
    TENGV VARCHAR(20),
    SDT VARCHAR(10)
);

ALTER TABLE MONHOC ADD MAGV VARCHAR(20);
ALTER TABLE MONHOC ADD CONSTRAINT FK_MAGV FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);


