CREATE DATABASE UNIT_5;

USE UNIT_5;

CREATE TABLE CLASS (
    CLASS_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CLASS_NAME VARCHAR(60) NOT NULL,
    CLASS_START_DATE DATETIME NOT NULL,
    CLASS_STATUS BIT
);

CREATE TABLE STUDENT (
    STUDENTID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME VARCHAR(30) NOT NULL,
    STUDENT_ADDRESS VARCHAR(50),
    STUDENT_PHONE VARCHAR(20),
    STUDENT_STATUS BIT,
    CLASS_ID INT NOT NULL,
    FOREIGN KEY (CLASS_ID)
        REFERENCES CLASS (CLASS_ID)
);

CREATE TABLE SUBJECTS (
SUB_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
SUB_NAME VARCHAR(30) NOT NULL,
SUB_CREDIT TINYINT NOT NULL DEFAULT(1) CHECK(SUB_CRESDIT >=1),
SUB_STATUS BIT DEFAULT(1)
);

CREATE TABLE MARK (
    MARK_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SUB_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    MARK FLOAT DEFAULT 0 CHECK (Mark BETWEEN 0 AND 100),
    EXAMTIMES TINYINT DEFAULT 1,
    UNIQUE (SUB_ID , STUDENT_ID),
    FOREIGN KEY (SUB_ID)
        REFERENCES Subject (SUB_ID),
    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT (STUDENT_ID)
);


